<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
<link type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,700" rel="stylesheet">
<link type="text/css" href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
<link type="text/css" href="https://cdn.secure.website/ws/1631048375/library/ripples.min.css" rel="stylesheet"> 
<script type="text/javascript" async="" src="https://ssl.google-analytics.com/ga.js"></script>
<script async="" src="//connect.facebook.net/en_US/fbds.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/arrive/2.4.1/arrive.min.js"></script>
<script type="text/javascript" src="https://cdn.secure.website/ws/1631048375/library/ripples.min.js"></script>
<script type="text/javascript" src="https://cdn.secure.website/ws/1631048375/library/material.min.js"></script>
<script type="text/javascript" src="https://cdn.secure.website/ws/1631048375/library/ui-common.min.js"></script>

<link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
@include('fixed-header')
<body>
	<section id="privacy-page" class="bg-white pb-20">
<div class="section-a main-section">
    <div class="aligner">
    <div class="main-section-row">
      <div class="main-section-text-column col-span-4">
      <h1 class="main-section-heading w-auto">
        Privacy Policy
      </h1>
      </div>
    </div>
    </div>      
</div>

		<div class="pt-12">
<div class="flex justify-center lg:justify-start pl-0 lg:pl-16">
    <div class="w-90">

      <div class="bg-white">
        <div class="">
      <p class="pb-4">Effective as of May 25, 2018</p>
      <h3 class="about-title">Our Commitment to Your Privacy</h3>

      <p class="pb-4">Your privacy on the Internet is of the utmost importance to us. At WebStarts.com, we want to make your online experience satisfying and safe and we are committed to protecting any and all information we gather from you under the compliance with data privacy laws.</p>
      <p class="pb-4">Please make sure to read and fully understand this policy prior to using any services provided by WebStarts.</p>

      <p class="pb-4">Because we gather certain types of information about our users, we feel you should fully understand the terms and conditions surrounding the capture and use of that information, as well as your rights and choices available to you regarding such information. </p>
      <p class="pb-4">This privacy statement discloses what information WebStarts gathers and how we use it. This  policy does not cover third party sites hosted by WebStarts. You would need to approach the site owners directly for any questions on their privacy policies.</p>
      <h3 class="about-title">Definitions</h3>
      <ul class="ml-4 pb-4 list-disc list-inside">
              
              <li class="pb-2">Personal Data</li>    
              <p class="ml-6 pb-2">Personal Data means data about a living individual who can be identified from that data (or from those and other information either in our possession or likely to come into our possession).
              
              <li class="pb-2">Usage Data</li>
              <p class="ml-6 pb-2">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
              
              <li class="pb-2">Cookies</li>  
              <p class="ml-6 pb-2">Cookies are small pieces of data stored on your device (computer or mobile device).</p>
              
              <li class="pb-2">Data Controller</li>
                <p class="ml-6 pb-2">Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
                <p class="ml-6 pb-2">For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
              
              <li class="pb-2">Data Processors (or Service Providers)</li>
                <p class="ml-6 pb-2">Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</p>
                <p class="ml-6 pb-2">We may use the services of various Service Providers in order to process your data more effectively.
          
              <li class="pb-2">Data Subject (or User)</li>
                <p class="ml-6 pb-2">Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
              
      </ul>
      <h3 class="about-title">Information Gathered by WebStarts.com</h3>

      <p class="pb-4">WebStarts.com gathers two types of information about users:</p>

      <ul class="ml-4 pb-4 list-disc list-inside">
        <li>Information that users provide through optional, voluntary submissions. These are voluntary submissions when creating a WebStarts account, such as your name or email address. Personally identifiable information may include, but is not limited to:<br />
          <br />
                  <ul class="ml-8 list-circle list-inside">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City<br />
                      <br />
                    </li>
                  </ul>
        </li>
        <li>Information WebStarts.com gathers through aggregated tracking, derived mainly by tallying page views throughout our sites. This information allows us to better tailor our content to users' needs and to help us better understand the demographics of our audience. Under no circumstances does WebStarts.com divulge any information about an individual user to a third party unless mandated by law.</li>
      </ul>

      <p class="pb-4">WebStarts.com Gathers User Information In The Following Processes: </p>

      <h3 class="about-title">Optional Voluntary Information</h3>

      <p class="pb-4">We offer the following free services, which require some type of voluntary submission of personal information by users:</p>

      <div class="indent">

      <h5 class="text-paragraph pb-2">Free Web Hosting</h5>
      <p class="pb-4">During the account creation process, the user is required to supply full name, username, password, and email address. Except as specified in this Privacy statement, we will not disclose any information about any individual user except to comply with applicable law or valid legal process or to protect the personal safety of our users or the public.</p>

      <p class="pb-4">You can access and update your personal information by logging in and visiting your  Account Settings and following the instructions on that page, or by contacting customer support. If you delete such information, it cannot be used by us or disclosed to third parties in the future. Even if you delete or change some personal information in our registration database, it may still be stored on other databases (including those kept for archival purposes).</p>

      <p class="pb-4">Any files uploaded or created on the WebStarts system are by nature of being hosted for the public and are thus publicly accessible. If you have content that you do not want to make publicy available on the internet, do not place that content on your website.</p>


      <h5 class="text-paragraph pb-2">"Email this to a friend" Service</h5>
      <p class="pb-4">Our site users can choose to electronically forward a link, page or documents to someone else by clicking "email this to a friend". Users must provide their email address, as well as that of the recipient. This information is used in the case of transmission errors and, of course, to let the recipient know who sent the email.</p>


      <h5 class="text-paragraph pb-2">Polling</h5>
      <p class="pb-4">We may offer interactive polls to users so they can easily share their opinions with other users and see what our audience thinks about important issues. Opinions or other responses to polls are aggregated and are not identifiable to any particular user. WebStarts.com may use a system to "tag" users after they have voted, so they can vote only once on a particular question. This tag is not correlated with information about individual users.</p>


      <h5 class="text-paragraph pb-2">Surveys</h5>
      <p class="pb-4">WebStarts.com may occasionally conduct optional user surveys to better target our content to our audience. We sometimes share the aggregated demographic information in these surveys with our sponsors, advertisers and partners. We never share any of this information about specific individuals with any third party. </p>
      </div>
      <h3 class="about-title">Usage tracking</h3>

      <p class="pb-4">WebStarts.com tracks user traffic patterns throughout all of our sites. However, we do not correlate this information with data about individual users. WebStarts.com does break down overall usage statistics according to a user's domain name, browser type and MIME type by reading this information from the browser string (information contained in every user's browser).</p>

      <p class="pb-4">WebStarts.com sometimes tracks and catalogs the search terms that users enter in our Search function, but this tracking is never associated with individual users. We use tracking information to determine which areas of our sites users like and don't like based on traffic to those areas. We do not track what individual users read, but rather how well each page performs overall. This helps us continue to build a better service for our users.</p>


      <h3 class="about-title">Cookies</h3>

      <p class="pb-4">We may place a text file called a "cookie" in the browser files of your computer. The cookie itself does not contain Personal Information although it will enable us to relate your use of this site to information that you have specifically and knowingly provided. But the only personal information a cookie can contain is information you supply yourself. A cookie can't read data off your hard disk or read cookie files created by other sites. WebStarts.com uses cookies to track user traffic patterns (as described above). Our advertising system delivers a one-time cookie to better track ad impressions and click rates.</p>

      <p class="pb-4">You can refuse cookies by turning them off in your browser. If you've set your browser to warn you before accepting cookies, you will receive the warning message with each cookie. You do not need to have cookies turned on to use this site. However, you do need cookies to participate actively in message boards, forums, polling and surveys.</p>
      <h3 class="about-title">Use of Data</h3>
          <p class="pb-4">WebStarts uses the collected data for various purposes:</p>
            <ul class="ml-4 pb-4 list-disc list-inside">
              <li>To provide and maintain our Service</li>
              <li>To notify you about changes to our Service</li>
              <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
              <li>To provide customer support</li>
              <li>To gather analysis or valuable information so that we can improve our Service</li>
              <li>To monitor the usage of our Service</li>
              <li>To detect, prevent and address technical issues</li>
              <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information      </li>
            </ul>
            <p class="pb-4">WebStarts.com uses any information voluntarily given by our users to enhance their experience in our network of sites, whether to provide interactive or personalized elements on the sites or to better prepare future content based on the needs and interests of our users.</p>

      <p class="pb-4">When we use tracking information to determine which areas of our sites users like and don't like based on traffic to those areas, we do not track what individual users read, but rather how well each page performs overall. This helps us continue to build a better service for you. We track search terms entered in Search function as one of many measures of what interests our users.</p>

      <p class="pb-4">WebStarts.com creates aggregate reports on user demographics and traffic patterns. This allows us to more effectively tailor advertising and promotions to our users.      </p>
      <h3 class="about-title">Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</h3>
            <p class="pb-4">If you are from the European Economic Area (EEA), WebStarts legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
            <p class="pb-4">WebStarts may process your Personal Data because:</p>
            <ul class="ml-4 pb-4 list-disc list-inside">
              <li>We need to perform a contract with you</li>
              <li>You have given us permission to do so</li>
              <li>The processing is in our legitimate interests and it's not overridden by your rights</li>
              <li>For payment processing purposes</li>
              <li>To comply with the law</li>
            </ul>
            <h3 class="about-title">Retention of Data</h3>
            <p class="pb-4">WebStarts will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p class="pb-4">WebStarts will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
            <h3 class="about-title">Transfer of Data</h3>
            <p class="pb-4">Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
            <p class="pb-4">If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</p>
          <p class="pb-4">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
            <p class="pb-4">WebStarts will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.     </p>
            <h3 class="about-title">Disclosure of Data</h3>
            <h5 class="text-paragraph">Disclosure for Law Enforcement:</h5>
            <p class="pb-4">Under certain circumstances, WebStarts may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
            <h5 class="text-paragraph">Legal Requirements:</h5>
          <p class="pb-4">WebStarts may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul class="ml-4 pb-4 list-disc list-inside">
              <li>To comply with a legal obligation</li>
              <li>To protect and defend the rights or property of WebStarts</li>
              <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>To protect the personal safety of users of the Service or the public</li>
              <li>To protect against legal liability      </li>
            </ul>
            <h3 class="about-title">Security of Data</h3>
            <p class="pb-4">The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
            <h3 class="about-title">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h3>
            <p class="pb-4">If you are a resident of the European Economic Area (EEA), you have certain data protection rights. WebStarts aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
            <p class="pb-4">If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
            <p class="pb-4">In certain circumstances, you have the following data protection rights:</p>
            <ul class="ml-4 pb-4 list-disc list-inside">
              <li class="pb-2">The right to access, update or to delete the information we have on you.</li>
                <p class="ml-6 pb-2">Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</p>
              
              <li class="pb-2">The right of rectification.</li> 
              <p class="ml-6 pb-2">You have the right to have your information rectified if that information is inaccurate or incomplete.</p>
              
              <li class="pb-2">The right to object.</li> 
              <p class="ml-6 pb-2">You have the right to object to our processing of your Personal Data.</p>
              
              <li class="pb-2">The right of restriction.</li> 
              <p class="ml-6 pb-2">You have the right to request that we restrict the processing of your personal information.</p>
             
              <li class="pb-2">The right to data portability.</li> 
              <p class="ml-6 pb-2">You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</p>
              
              <li class="pb-2">The right to withdraw consent.</li> 
              <p class="ml-6 pb-2">You also have the right to withdraw your consent at any time where WebStarts relied on your consent to process your personal information.</p>
              
            </ul>
            <p class="pb-4">Please note that we may ask you to verify your identity before responding to such requests.</p>
            <p class="pb-4">You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
            <h3 class="about-title">Service Providers</h3>
            <p class="pb-4">We may employ third party companies and individuals to facilitate our Service (&quot;Service Providers&quot;), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
            <p class="pb-4">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
            <h5 class="text-paragraph">Analytics</h5>
            <p class="pb-4">We may use third-party Service Providers to monitor and analyze the use of WebStarts.com.</p>
            <ul class="ml-4 pb-4 list-disc list-inside">
              <li class="pb-2">Google Analytics</li>
                <p class="pb-4 ml-6">Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
                <p class="pb-4 ml-6">You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>
                <p class="pb-4 ml-6">For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: <a class="text-primarycolor hover:underline" href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a></p>
            </ul>
            <h5 class="text-paragraph pb-2">Payments</h5>
            <p class="pb-4">We  provide paid products and/or services and use third-party services for payment processing (e.g. payment processors).</p>
            <p class="pb-4">We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
            <p class="pb-4">The payment processor we use is Stripe and their Privacy Policy can be found here: <a class="text-primarycolor hover:underline" href="https://stripe.com/us/privacy">https://stripe.com/us/privacy</a></p>
            <h3 class="about-title">Links to Other Sites</h3>
          <p class="pb-4">Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
            <p class="pb-4">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
            <h3 class="about-title">Children's Privacy</h3>
            <p class="pb-4">Consistent with the Federal Children's Online Privacy Protection Act of 1998 (COPPA), we will never knowingly request personally identifiable information from anyone under the age of 13 since we do not allow anyone under the age of 13 to sign up. </p>
            <h3 class="about-title">No Spyware / Adware</h3>

      <p class="pb-4">We have a strict policy against spyware and adware and apply this to all WebStarts users as well.</p>


      <h3 class="about-title">Opt-out Policy</h3>

      <p class="pb-4">We give users options wherever necessary and practical. Such choices include:</p>

      <p class="pb-4">Opting not to participate in certain interactive areas, which completely alleviates the need to gather any personally identifiable information from our users.</p>

      <p class="pb-4">Opting to delete and close their WebStarts account at any time for any reason.</p>


      <h3 class="about-title">Your Consent </h3>

      <p class="pb-4">By using this site, you consent to the collection and use of this information by WebStarts.com. If we decide to change our privacy policy, we will post those changes on this page so that you are always aware of what information we collect, how we use it and under what circumstances we disclose it.</p>
      <h3 class="about-title">Contact Us</h3>
          <p class="pb-4">If you have any questions about this Privacy Policy, please contact us:</p>
            <ul class="ml-4 pb-4 list-disc list-inside">
              <li>By email: support@webstarts.com</li>
              <li>By visiting our Contact page: https://www.webstarts.com/contact</li>
              <li>By phone: 1-800-805-0920      </li>
            </ul>
          
        </div>
      </div>

    </div>
</div>
			
		</div>
    <div class="text-center py-8 aligner">
            <a class="m-0 w-90 md:w-210px block btn btn-lg btn-secondary btn-raised" href="/templates">Sign up. It's free.</a>
    </div>
	</section>
</body>
@include('footer')